### ISSUE TITLE
unexpected whitespace character when unicode 65279 (utf-8 bom) encountered

### ISSUE THREAD

**Issue by ichernev** [benjamn/recast#148]
If recast.parse encounters character code 65279, recast throws an exception

```javascript
AssertionError: "unexpected whitespace character" undefined ""
    at countSpaces (/home/iskren/src/moment/node_modules/recast/lib/lines.js:108:20)
    at /home/iskren/src/moment/node_modules/recast/lib/lines.js:140:21
    at Array.map (native)
    at fromString (/home/iskren/src/moment/node_modules/recast/lib/lines.js:136:46)
    at Object.parse (/home/iskren/src/moment/node_modules/recast/lib/parser.js:16:17)
```

This can be achieved by reading a file with utf-8 bom and converting to string:
```javascript
> x = fs.readFileSync("file_with_utf8_bom.js", {encoding: "utf8"})  // 0x EF BB BF first bytes
> x.charCodeAt(0)
65279
```

Sample file with utf-8 bom: https://raw.githubusercontent.com/moment/moment/2.9.0/test/locale/he.js

Not sure if this is a fs.readFileSync issue, or recast issue.

**Comment by benjamn** [comment]
This is just Recast being conservative/paranoid. The goal is to represent the indentation of each line with a number rather than a string of whitespace, so that we can tolerate weird intermediate states where indentations are occasionally negative, and so that we don't have to worry about the difference between tabs and spaces when doing that math.

In addition to the character you mentioned, it turns out there are a number of other kinds of spaces:
```js
var spacePattern = /\s/;
var spaceMap = Object.create(null);
for (var i = 0; i < 0xffff; ++i) {
  var ch = String.fromCharCode(i);
  if (spacePattern.test(ch)) {
    spaceMap[i] = ch;
  }
}
console.log(spaceMap);
```
This prints:
```js
{ '9': '\t',
  '10': '\n',
  '11': '\u000b',
  '12': '\f',
  '13': '\r',
  '32': ' ',
  '160': ' ',
  '5760': ' ',
  '6158': '᠎',
  '8192': ' ',
  '8193': ' ',
  '8194': ' ',
  '8195': ' ',
  '8196': ' ',
  '8197': ' ',
  '8198': ' ',
  '8199': ' ',
  '8200': ' ',
  '8201': ' ',
  '8202': ' ',
  '8232': ' ',
  '8233': ' ',
  '8239': ' ',
  '8287': ' ',
  '12288': '　',
  '65279': '﻿' }
```
For reference, here's the offending `countSpaces` function:
```js
function countSpaces(spaces, tabWidth) {
    var count = 0;
    var len = spaces.length;

    for (var i = 0; i < len; ++i) {
        var ch = spaces.charAt(i);

        if (ch === " ") {
            count += 1;

        } else if (ch === "\t") {
            assert.strictEqual(typeof tabWidth, "number");
            assert.ok(tabWidth > 0);

            var next = Math.ceil(count / tabWidth) * tabWidth;
            if (next === count) {
                count += tabWidth;
            } else {
                count = next;
            }

        } else if (ch === "\r") {
            // Ignore carriage return characters.

        } else {
            assert.fail("unexpected whitespace character", ch);
        }
    }

    return count;
}
```
My question for you: do all of those characters (except for `\n`, `\t`, `\r`) deserve to be treated the same as a simple space (`String.fromCharCode(0x20)`)? In particular, the character you mentioned is the famous "zero-width non-breaking space" (`0xfeff`), so maybe it should count as zero spaces?

**Comment by ichernev** [comment]
If its zero width by definition I dont see why not cosider it as zero indentation. Moreover, if it came from bom, it would be in the begining of first line only, so 0 indentation is the right choice.

Thank you for the detailed explanation!
