### ISSUE TITLE
Indentation gone when modifying switch statement

### ISSUE THREAD

**Issue by grabbou** [benjamn/recast#180]
Hey,

When adding a new case to a statement formatted like below:

```
switch(action) {

  case 'test': 
    // do something
    break;

}
```

it gets printed as 

```
switch(action) {
case 'test':
  break;
case 'newlyAdded':
  break;
}
```

Indentation is only broken inside a switch statement. Any quick tips on how to fix that + preserve line breaks? (If anyone knows how to programatically force line break when pushing an element to e.g. `program.body`, I'd appreciate)

**Comment by benjamn** [comment]
This behavior is expected. Most IDEs I've encountered indent `case` at the same level as `switch`, perhaps because `case`s are a lot like statement labels, and I cargo-culted that common style into the Recast pretty-printer (the printer code itself contains [a big `switch` statement](https://github.com/benjamn/recast/blob/24ebc0e110aed78326fc1278d888912c4a53cb7b/lib/printer.js#L164-L165) that follows this style).

The pretty-printer kicks in here because you're adding a new child to a list of children, so the parent has to reprint the whitespace around the children. This case might seem easy enough to handle more surgically, but it's tricky to do the right thing when the children change in more complicated ways, without just pretty-printing the whitespace.

That said, I agree that it would be nice of Recast didn't inject its opinion in cases like this. The printer has a function called [`printStatementSequence`](https://github.com/benjamn/recast/blob/24ebc0e110aed78326fc1278d888912c4a53cb7b/lib/printer.js#L1282) that preserves whitespace around statements in a sequence of statements, so perhaps the same trick can be applied to `case`s in a `switch` statement.

Another improvement might be to infer the indentation of `case` labels in a given `switch` statement, which seems feasible because no `switch` statement will ever have zero `case` or `default` labels (so we don't have to worry about the case where we can't infer the indentation. I think I like that idea more.

For cases where you absolutely need to add a newline, you can trick the printer by inserting a string literal `"\n"` into the list of `SwitchCase` elements. It's not technically valid according to the AST, but the printer will print it anyway: https://github.com/benjamn/recast/blob/24ebc0e110aed78326fc1278d888912c4a53cb7b/lib/printer.js#L159
