### ISSUE TITLE
Depends on unreleased ast-types 0.9.1

### ISSUE THREAD

**Issue by SnarkBoojum** [benjamn/recast#338]
Hi,

I don't understand the commit adding the depend on a recently released ast-types 0.9.1... since it wasn't released!

Could you clarify things?

Thanks,

Snark on #debian-js

**Comment by benjamn** [comment]
I've now pushed a `v0.9.1` tag to the `ast-types` repository (see [releases](https://github.com/benjamn/ast-types/releases)). I hope that helps.

I consider a release of either of these libraries to mean publishing them to `npm` (which I definitely did before you filed this issue), so I'm a bit confused as to why you would be depending on GitHub release tags instead of `npm` versions.

**Comment by SnarkBoojum** [comment]
I depend on github release tags because I'm packaging for Debian, so I directly check upstream for releases, not npm, which is another distribution.

Notice that something like:

     npm version 0.9.2 -m "Readying new version %s"

would update package.json, create a commit with that change and the above message with the version instead of the %s and tag said commit accordingly, if I am to believe [this documentation](https://docs.npmjs.com/cli/version).

I hope that helps,

Snark on #debian-js
