### ISSUE TITLE
missing parentheses in printed code causes syntax error

### ISSUE THREAD

**Issue by zoltan-mihalyi** [benjamn/recast#351]
```javascript
recast.print({
    type: "AssignmentExpression",
    left: {
        type: "MemberExpression",
        computed: false,
        object: {type: "ObjectExpression", properties: []},
        property: {type: "Identifier", name: "x"}
    },
    operator: "=",
    right: {type: "Literal", value: 42}
}).code // "{}.x = 42"
```

I checked that parsing the expected result with correct parentheses
```javascript
recast.parse("({}).x=42") 
```
produces the same AST (which is printed with parentheses), the only difference is the existence of "original" and "loc" properties.
It seems like the printer thinks it is not necessary to print parentheses, but when the parsed expression has parentheses, it prints them.

I discovered a similar problem:

```javascript
var callee = recast.parse('typeof a==="function"?a:b').program.body[0].expression;
recast.print({type:"NewExpression", callee:callee, arguments:[]); // 'new typeof a==="function"?a:b()' 
```

In this case, it seems like the printer thinks it is neccessary to print parentheses (when i don't use a parsed expression object) but because the parsed expression hasn't, it does not print any.

**Comment by benjamn** [comment]
Isn't this code legal, though?
```js
var a = { a: 1 }.a;
console.log(a);
```
It's possible there's a problem with the [logic](https://github.com/zoltan-mihalyi/recast/blob/82640f56dc2a038b3430b0fdf3be65a9d53d429e/lib/fast-path.js#L353-L356) in `FastPath.prototype.needsParens` that checks whether an AST node can appear as the first node in a statement. Specifically, parentheses are needed when the opening `{` is the first syntax in the statement, but not otherwise.

**Comment by zoltan-mihalyi** [comment]
You were right, the AssignmentExpression case was missing in firstInStatement method.
