### ISSUE TITLE
recast.prettyPrint produces invalid JavaScript

### ISSUE THREAD

**Issue by nfroidure** [benjamn/recast#360]
Simply do this in the node terminal:
```
> var recast  = require('recast')
undefined
> var ast = recast.parse('{ x }')
undefined
> recast.print(ast)
PrintResult { code: '{ x }' }
> recast.print(ast).code
'{ x }'
> recast.prettyPrint(ast).code
'{\n    x;\n}'
> { x; }
ReferenceError: x is not defined
    at repl:1:3
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
```

I am using: `"recast": "^0.11.18"`

**Comment by demoneaux** [comment]
This is not an issue with Recast, executing `{ x }` without any other code would cause the error as well. The `{` would be taken as starting a new block statement, with `x` being accessed within the block. Since `x` is not defined, the error occurs. If you are trying to make an object with variable `x`, you need to let the parser know that the `{` is part of an expression, by doing something like `({ x })` or `let obj = { x };`.

**Comment by nfroidure** [comment]
@demoneaux thanks for the explanation, i've been mistaken by doing `{ window }` in the browser which worked since window is defined it worked actually, at least in Chrome.
