### ISSUE TITLE
For loop printed with extra semicolon when initialized with `let` and body replaced with block

### ISSUE THREAD

**Issue by outoftime** [benjamn/recast#377]
Probably easiest to start with a reduction:

```js
const recast = require('recast');
const b = recast.types.builders;

const ast = recast.parse(`
  for (let i = 0; i < 1; i++)
    console.log(i);
`);
const loop = ast.program.body[0];

loop.body = b.blockStatement([]);

console.log(recast.print(ast).code);
```

The output is:

```js
for (let i = 0;; i < 1; i++)
  {}
```

Note the extra semicolon after the loop initialization statement.

From playing around, in order to see this bug, you need to:

* Initialize the loop with a `let` (works fine with a `var`)
* Have the original loop contain a single-statement, non-block body
* Replace the body with a block statement (doesn’t matter what’s in the block)

Observed with recast 0.11.22

**Comment by benjamn** [comment]
This appears to be a parser bug, since `loop.init.loc.{start,end}` wrongly includes the `;` character from the original code. In other words, `loop.init.loc.end.column` is one character too large.

Fortunately, parser bugs that lead to faulty `.loc.{start,end}` information can usually be fixed in [`util.fixFaultyLocations`](https://github.com/benjamn/recast/blob/412aaf89d3993a58b35c8f255a1c6751540064d9/lib/util.js#L147).
