### ISSUE TITLE
Failing to print comments in the right location from flow parsed AST

### ISSUE THREAD

**Issue by mitermayer** [benjamn/recast#423]
```javascript
const recast = require('recast');
const flowParser = require('flow-parser');

const fixture = `
function() {
  // some comment
}
`;
console.log(recast.print(flowParser.parse(fixture)).code);
```

The above is generating the following output:

```javascript
// some comment
function() {
}
```

Expected out put should be:

```javascript
function() {
  // some comment
}
```

**Comment by benjamn** [comment]
Instead of parsing with `flowParser.parse` directly, you should specify `flowParser` as `options.parser` when you call `recast.parse`:
```js
console.log(recast.print(recast.parse(fixture, {
  parser: flowParser
})).code);
```
If you don't give `recast.parse` a chance to process the AST, you won't get any benefits from using `recast.print` over just pretty-printing the whole tree.

More importantly, `recast.parse` is where the comment attachment logic happens, so this may help solve the problem, though I haven't tried it out.

**Comment by benjamn** [comment]
I wonder if maybe `recast.print` should warn if it doesn't find any nodes with `.original` properties, since then it produces the same result as `recast.prettyPrint`, just slightly slower because it will keep trying to reuse the original source.

**Comment by mitermayer** [comment]
@benjamn just confirmed that by passing the parser itself I no longer get that same behaviour. 

I also agree with the strategy of printing a warning when no `.original` properties are found. 

Would also be helpful to also include on the `README` some notes explaining that printing a parsed AST by another parser does not produce same result as when passing the parser explicity to recast.

Thank you for all the info :) very helpful
