### ISSUE TITLE
flow types not supported? Or formatting not retained?

### ISSUE THREAD

**Issue by eirslett** [benjamn/recast#428]
Looks like flow types are not supported out of the box:

```javascript
const code = `
function foo (data: {| firstName: string, lastName: string |}): string {
  return data.firstName + ' ' + data.lastName;
}
`
const ast = recast.parse(code); // Error: Line 2: Unexpected token :
```

I tried using the babylon parser, and it works:

```javascript
const code = `
function foo (data: {| firstName: string, lastName: string |}): string {
  return data.firstName + ' ' + data.lastName;
}
`

const ast = babylon.parse(code, {
  sourceType: 'module',
  plugins: ['jsx', 'flow']
});

console.log(recast.print(ast).code);
```

The problem is that the formatting is not retained. This is the output:

```javascript
function foo(
    data: {|
        firstName: string,
        lastName: string,
    |}
): string {
    return data.firstName + " " + data.lastName;
}
```

It looks like it changes the formatting of code that is not flow-related as well, for example this:

```javascript
function a () {
  return (1 + 
    (2 + 
      (3 + 4
      )
    )
  );
}
```

output:

```javascript
function a() {
    return 1 + (2 + (3 + 4));
}
```

I need to do some modifications on the AST tree, and then print the result (with formatting). Is it possible to do that with code that uses flow and JSX?

**Comment by benjamn** [comment]
Sorry for the delayed response @eirslett.

The key is to use `recast.parse` instead of calling `babylon.parse` directly:
```js
recast.parse(code, {
  parser: {
    parse(code) {
      return babylon.parse(code, {
        sourceType: 'module',
        plugins: ['jsx', 'flow']
      });
    }
  }
});
```
Why is this so important? When you call `recast.parse`, it makes a shadow copy of the AST before returning it to you, with every AST node attached to its copy via an `.original` property. This is the information `recast.print` uses to detect where the AST has been modified, so that it can preserve formatting for parts of the AST that were not modified.

When you pass a raw `babylon.parse`d AST to `recast.print`, it's more than happy to print it for you, but it looks like an AST where every node has been replaced, since none of the nodes have their `.original` properties intact, so the end result is that everything gets re-pretty-printed.

For what it's worth, in https://github.com/benjamn/recast/pull/472 I'm working on some preconfigured parsers that would simplify the code above:
```js
recast.parse(code, { parser: require("recast/parsers/flow") });
```

**Comment by benjamn** [comment]
This inspired me to add a section to the README about how to use an alternate parser: https://github.com/benjamn/recast/blob/master/README.md#using-a-different-parser

**Comment by benjamn** [comment]
Closing because I think my explanation clears things up. If you run into any specific problems when using a custom parser, please open a new issue!
