### ISSUE TITLE
Preserve Array Indentation

### ISSUE THREAD

**Issue by Snugug** [benjamn/recast#429]
I have an array of objects and I'm inserting a new item in to the array. I would like to preserve the spacing and alignment of the original array in the new output array, but I can't seem to figure out how without manually hacking `loc`. Source vs Output:

**Source**
```js
const routes = [
  {
    path: '/',
    name: 'index',
    component: landing
  },
  {
    path: '/vacation-holiday',
    name: 'vacation-holiday',
    component: vacationHoliday
  },
  {
    path: '*',
    redirect: '/'
  },
];
```

**Output**
```js
const routes = [{
  path: '/',
  name: 'index',
  component: landing
}, {
  path: '/vacation-holiday',
  name: 'vacation-holiday',
  component: vacationHoliday
}, {
  path: '/foo',
  name: 'foo',
  component: foo,
}, {
  path: '*',
  redirect: '/'
}];
```

Ultimately it will still pass our linter but the recast output is less human-editable than the source file and I'd like to preserve that

**Comment by benjamn** [comment]
You can change existing elements of the array expression, but if you add or remove elements, that triggers reprinting of the enclosing syntax (`[`, `]`, `,`s), which is subject to the rules of Recast's pretty-printer.

**Comment by benjamn** [comment]
This is working as designed, per my previous comment.

Inserting new elements into a sequence like an `ArrayExpression` or `ObjectExpression` requires rerunning the pretty-printer for the parent node, since the parent is responsible for printing syntax like brackets, braces, and commas (the stuff in between / outside the element nodes). There's no reasonable way to print just the inserted child plus a leading or trailing comma, without making the child's pretty-printer implementation partly responsible for the parent's syntax.

The best way forward here is probably something like https://github.com/benjamn/recast/issues/226, so that you can customize the behavior of the pretty-printer to your liking.

**Comment by innovation-stack** [comment]
@benjamn: Any workaround that you think can be leveraged to preserve indentation?
