### ISSUE TITLE
parsers/esprima.js - doesn't forward `range` option

### ISSUE THREAD

**Issue by tchetwin** [benjamn/recast#519]
Normalized options contain a `range` property: https://github.com/benjamn/recast/blob/5f0e4e6cf7512031d4c4de0303cc5348ab72b0d2/lib/options.js#L118

This is passed to the `parse` method of the selected parser: https://github.com/benjamn/recast/blob/5f0e4e6cf7512031d4c4de0303cc5348ab72b0d2/lib/parser.js#L32

The (default) esprima parser appears not to forward this param to esprima in this call: https://github.com/benjamn/recast/blob/5f0e4e6cf7512031d4c4de0303cc5348ab72b0d2/parsers/esprima.js#L14

Would it make sense to forward `range` here as `tolerant`/`tokens` are?

**Comment by benjamn** [comment]
Recast uses `.loc.{start,end}.{line,column}` rather than `.range` for its own purposes, in part because almost any change to the code invalidates all subsequent `.range` information, whereas `.loc` is slightly more robust (e.g. if you just change one line without introducing/removing lines). That said, I don't see why we couldn't expose the `.range` information, too.

**Comment by tchetwin** [comment]
I think the behaviour changed from version 0.12.6 to 0.15.2 (haven't bisected to see exactly when). In 0.12.6 passing `{ range: true }` among options resulted in `range` keys in the output, in 0.15.2 it doesn't make a difference.

**Comment by benjamn** [comment]
Fixed by https://github.com/benjamn/recast/pull/536.
